### ISSUE TITLE
这样处理的话，在百度初始化引擎的时候会崩溃。

### ISSUE THREAD

**Issue by limingnie** [madordie/Demo-PodspecUseBMK#1]

**Comment by limingnie** [comment]
objc[13172]: Class BMSDKKeychainItemWrapper is implemented in both /private/var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/Frameworks/BMK.framework/BMK (0x10119b2e8) and /var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/BaiduMapKit-pods (0x1006a2b90). One of the two will be used. Which one is undefined.
objc[13172]: Class BMSDKUDID is implemented in both /private/var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/Frameworks/BMK.framework/BMK (0x10119b388) and /var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/BaiduMapKit-pods (0x1006a2be0). One of the two will be used. Which one is undefined.
objc[13172]: Class systemConfigModel is implemented in both /private/var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/Frameworks/BMK.framework/BMK (0x10119b5b8) and /var/containers/Bundle/Application/8BF75969-E376-4B43-9E09-4B885FEEEF5B/BaiduMapKit-pods.app/BaiduMapKit-pods (0x1006a2c80). One of the two will be used. Which one is undefined.
。。。。。
log这里也提示说两边都有引入。

**Comment by madordie** [comment]
老铁  关于静态库的支持cocoapods已经支持的想到的好了😂 ，这个项目是在当时framework不支持静态库的时候搞得😂 ，另外 `One of the two will be used. Which one is undefined `这个警告并不会引起崩溃

**Comment by limingnie** [comment]
那对于私有pod依赖百度地图的方法有更优的解决办法嘛？你的脚本对于封私有framework的确有用，但是这个方法是会导致私有framework和主工程都有一套自己的初始方法，甚至得配两个key，百度OK，难过的是谷歌地图不OK。
